apiVersion: v1
kind: Secret
metadata:
  name: app-database-secret
  namespace: tickets
type: Opaque
stringData:
  DATABASE_URL: postgresql://tickets_user:tickets_password@postgres-service:5432/tickets_db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: tickets
  labels:
    app: inventory
spec:
  replicas: 2

  selector:
    matchLabels:
      app: inventory

  template:
    metadata:
      labels:
        app: inventory

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: inventory

      containers:
        - name: inventory
          image: tickets-inventory:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-database-secret
                  key: DATABASE_URL

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 300m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: tickets
spec:
  type: ClusterIP

  selector:
    app: inventory

  ports:
    - name: http
      port: 8000
      targetPort: 8000