apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: tickets
  labels:
    app: payments

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payments

  template:
    metadata:
      labels:
        app: payments

    spec:
      nodeSelector:
        sitio: nodo-b

      containers:
        - name: payments
          image: tickets-payments:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: MIN_DELAY_MS
              value: "500"

            - name: MAX_DELAY_MS
              value: "2500"

            - name: FAILURE_RATE
              value: "0.15"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 300m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: tickets

spec:
  type: ClusterIP

  selector:
    app: payments

  ports:
    - name: http
      port: 8000
      targetPort: 8000